version: '3.8'
services:
  app:
    image: ghcr.io/socfortress/copilot:latest
    volumes:
      - ./backend/data:/opt/copilot/backend/data
    network_mode: "host"
    environment:
      SERVER_IP: ${SERVER_IP}
      VITE_API_URL: ${VITE_API_URL}
      VITE_TOKEN_DEBOUNCE_TIME: ${VITE_TOKEN_DEBOUNCE_TIME}
      VITE_UNCOMMITTED_JOURNAL_ENTRIES_THRESHOLD: ${VITE_UNCOMMITTED_JOURNAL_ENTRIES_THRESHOLD}
      VITE_HEALTHCHECKS_INTERVAL: ${VITE_HEALTHCHECKS_INTERVAL}
      WAZUH_INDEXER_URL: ${WAZUH_INDEXER_URL}
      WAZUH_INDEXER_USERNAME: ${WAZUH_INDEXER_USERNAME}
      WAZUH_INDEXER_PASSWORD: ${WAZUH_INDEXER_PASSWORD}
      WAZUH_MANAGER_URL: ${WAZUH_MANAGER_URL}
      WAZUH_MANAGER_USERNAME: ${WAZUH_MANAGER_USERNAME}
      WAZUH_MANAGER_PASSWORD: ${WAZUH_MANAGER_PASSWORD}
      GRAYLOG_URL: ${GRAYLOG_URL}
      GRAYLOG_USERNAME: ${GRAYLOG_USERNAME}
      GRAYLOG_PASSWORD: ${GRAYLOG_PASSWORD}
      SHUFFLE_URL: ${SHUFFLE_URL}
      SHUFFLER_API_KEY: ${SHUFFLER_API_KEY}
      DFIR_IRIS_URL: ${DFIR_IRIS_URL}
      DFIR_IRIS_API_KEY: ${DFIR_IRIS_API_KEY}
      VELOCIRAPTOR_URL: ${VELOCIRAPTOR_URL}
      VELOCIRAPTOR_API_KEY_PATH: ${VELOCIRAPTOR_API_KEY_PATH}
      SUBLIME_URL: ${SUBLIME_URL}
      SUBLIME_API_KEY: ${SUBLIME_API_KEY}
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_API_KEY: ${INFLUXDB_API_KEY}
      INFLUXDB_ORG_AND_BUCKET: ${INFLUXDB_ORG_AND_BUCKET}
      ASK_SOCFORTRESS_URL: ${ASK_SOCFORTRESS_URL}
      ASK_SOCFORTRESS_API_KEY: ${ASK_SOCFORTRESS_API_KEY}
      SOCFORTRESS_THREAT_INTEL_URL: ${SOCFORTRESS_THREAT_INTEL_URL}
      SOCFORTRESS_THREAT_INTEL_API_KEY: ${SOCFORTRESS_THREAT_INTEL_API_KEY}
      CORTEX_URL: ${CORTEX_URL}
      CORTEX_API_KEY: ${CORTEX_API_KEY}
      GRAFANA_URL: ${GRAFANA_URL}
      GRAFANA_USERNAME: ${GRAFANA_USERNAME}
      GRAFANA_PASSWORD: ${GRAFANA_PASSWORD}
      WAZUH_WORKER_PROVISIONING_URL: ${WAZUH_WORKER_PROVISIONING_URL}
    ports:
      - "5000:5000"
      - "5173:5173"
