site_name: SOCFortress CoPilot
theme:
    name: material
    features:
        - navigation.tabs
        - navigation.sections
        - toc.integrate
        - navigation.top
        - search.suggest
        - search.highlight
        - content.tabs.link
        - content.code.annotation
        - content.code.copy

    language: en
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
          primary: teal
          accent: purple
        - scheme: slate
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
          primary: teal
          accent: lime

plugins:
    - mkdocstrings:
    - autorefs

nav:
    - Home: index.md
    - Connectors: connectors.md
    - Agents: agents.md
    - Alerts: alerts.md
    - Artifacts: artifacts.md
    - Cases: cases.md
    - Graylog: graylog.md

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
          generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
    &copy; 2023 <a href="https://github.com/socfortress/CoPilot"  target="_blank" rel="noopener">SOCFortress CoPilot</a>
